version: "0.0.{build}"
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}-preview"
branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore src/Iot.Device.Model.sln --verbosity q
build_script:
  - cmd: dotnet build src/Iot.Device.Model.sln -c Release
after_build:
  # For once the build has completed
  - cmd: dotnet pack src/Iot.Device.Model.sln -o pacakges -c Release
artifacts:
  - path: "pacakges/**/*.nupkg"
    name: NugetPacakges

clone_depth: 1
test_script:
    - cmd: dotnet test src/Iot.Device.Model.sln
on_finish:
  # any cleanup in here
deploy:
  - provider: NuGet
    api_key:
      secure: 2rVyhSP7VBev5AaKvwPSXGY3Jc0Vhx4DKyDuc1k6TxyE6E3joCACpxG+AFyFNN6h
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: master
